[project]
name = "macau-weather-mcp"
version = "0.1.0"
description = "Macau weather HTTP streamable based MCP server."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.22.0",
]
